### ISSUE TITLE
Crash only Android Emulator.

### ISSUE THREAD

**Issue by benevbright** [bgryszko/react-native-circular-progress#104]
Hi, guys.

It works great on Android real devices. 
But don't you guys face the crashes on Android emulator?

React-Native version : 0.51.0
plugin version : 0.1.0
Tested Emulator: API 23 Pixel / API 23 Nexus 10 
It crashes without any error or red screen. 

I tested example app in this repo. It gives the same result.

Thanks.

**Comment by markusl** [comment]
Hi! Could you include more information about the issue. I tried with one Android emulator and the latest version worked just fine. What do you mean by "crashing" in this case?

**Comment by benevbright** [comment]
Hm.. i “crashed” without any log or red screen. I put this circular progresses on the Flatlist items.

**Comment by kurtsergey** [comment]
I think I have same issue.
Sometimes app just closes, but I see in logcat the same problem.

![screenshot_1515079571](https://user-images.githubusercontent.com/4003705/34570482-fb5f2082-f17c-11e7-926d-56d69f6c774b.png)

01-04 18:28:08.560  6243  7295 E unknown:ReactNative: Exception in native call
01-04 18:28:08.560  6243  7295 E unknown:ReactNative: com.facebook.react.bridge.JSApplicationIllegalArgumentException: Error while updating property 'd' in shadow node of type: ARTShape
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:113)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:154)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:58)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:298)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.UIImplementation.updateView(UIImplementation.java:319)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.UIManagerModule.updateView(UIManagerModule.java:384)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at android.os.Handler.handleCallback(Handler.java:790)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at android.os.Looper.loop(Looper.java:164)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at java.lang.Thread.run(Thread.java:764)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative: Caused by: java.lang.reflect.InvocationTargetException
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at java.lang.reflect.Method.invoke(Native Method)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:102)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   ... 15 more
01-04 18:28:08.560  6243  7295 E unknown:ReactNative: Caused by: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `double', but had type `null'
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.bridge.ReadableNativeArray.getDouble(Native Method)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.views.art.PropHelper.toFloatArray(PropHelper.java:50)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.views.art.PropHelper.toFloatArray(PropHelper.java:31)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   at com.facebook.react.views.art.ARTShapeShadowNode.setShapePath(ARTShapeShadowNode.java:65)
01-04 18:28:08.560  6243  7295 E unknown:ReactNative:   ... 17 more

**Comment by dancherb** [comment]
Same problem here - wouldn't have realised it still worked on my actual device if not for this thread

**Comment by hanpei** [comment]
i found the same issue here: https://github.com/facebook/react-native/issues/17937

> Third Update: I changed the graphics rendering from 'automatic' to 'software' and it now works!

**Comment by CoodeZhang** [comment]
I have same issue.
![krp fs28dqq6 i92 fahek](https://user-images.githubusercontent.com/13991223/38453450-820f39b0-3a88-11e8-9ca5-54dec45658ae.png)

```
performLinearAnimation(toValue, duration) {
		const { onLinearAnimationComplete } = this.props;

		Animated.timing(this.state.chartFillAnimation, {
			toValue: toValue,
			easing: Easing.linear,
			duration: duration,
			useNativeDriver: true,
		}).start(onLinearAnimationComplete);
	}
```
when I set the useNativeDriver,It crashed.

**Comment by Jacse** [comment]
I'm closing this for inactivity, but feel free to comment if you still experience this.
