### ISSUE TITLE
Testing with Jest causes Invariant Violation

### ISSUE THREAD

**Issue by jbolter** [bgryszko/react-native-circular-progress#60]
I am trying to use Jest Snapshot testing and am having an issue with this library.  When I try to create a snapshot test with the AnimatedCircularProgress component I run into this warning which causes the snapshot to fail to be created.  I traced it down to the Surface element in the CircularProgress component.  If I remove the Surface and Group elements then the tests will run without the warning.

Anyone have any ideas? I haven't found much when searching for this issue.

`Warning: Exception thrown by hook while handling onSetChildren: Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (4 has parents 2 and 3).
      Invariant Violation: Expected onBeforeMountComponent() parent and onSetChildren() to be consistent (4 has parents 2 and 3).
          at invariant (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/fbjs/lib/invariant.js:44:15)
          at Object.onSetChildren (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react/lib/ReactComponentTreeHook.js:186:78)
          at callHook (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactDebugTool.js:27:8)
          at emitEvent (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactDebugTool.js:39:7)
          at Object.onSetChildren (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactDebugTool.js:311:5)
          at ReactTestComponent.setChildrenForInstrumentation (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactMultiChild.js:157:38)
          at ReactTestComponent.mountChildren (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactMultiChild.js:245:39)
          at ReactTestComponent.mountComponent (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactTestRenderer.js:62:10)
          at Object.mountComponent (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactReconciler.js:46:35)
          at ReactCompositeComponentWrapper.performInitialMount (/Users/jbolter/work/dev/git/apps/msbuddy-rn/node_modules/react-test-renderer/lib/ReactCompositeComponent.js:371:34)`

**Comment by flavordaaave** [comment]
I'm also running into an error when using Jest but mine looks a bit different:
```
React caught an error thrown by ARTSurfaceView. You should fix this error in your code. Consider adding an error boundary to your tree to customize error handling behavior.
      
      TypeError: Cannot set property '_currentElement' of undefined
      
      The error is located at: 
          in ARTSurfaceView (created by Surface)
          in Surface (created by CircularProgress)
          in View (created by View)
          in View (created by CircularProgress)
          in CircularProgress (created by AnimatedComponent)
          in AnimatedComponent (created by AnimatedCircularProgress)
          in AnimatedCircularProgress (created by PackageFillStatus)
          in View (created by View)
          in View (created by PackageFillStatus)
          in View (created by View)
          in View (created by PackageFillStatus)
          in PackageFillStatus (created by Component)
          in View (created by View)
          in View (created by Component)
          in Component (created by Connect(Component))
          in Connect(Component)
          in Provider
```
But again the ARTSurfaceView seems to be the problem...

**Comment by lekenny** [comment]
@flavordaaave   Have you solved this problem?

**Comment by joaosilva05** [comment]
Having the same issue

**Comment by ajaxmac** [comment]
Add this to your test file to mock:
`jest.mock("react-native-circular-progress", () => 'CircularProgress');`

**Comment by markusl** [comment]
If there's something to fix on the library side PR's are always welcome :)
